import * as day1 from "./day1/main.js";
import * as day2 from "./day2/main.js";
import * as day3 from "./day3/main.js";
import * as day4 from "./day4/main.js";
import * as day5 from "./day5/main.js";
import * as day6 from "./day6/main.js";
import * as day7 from "./day7/main.js";
import * as day8 from "./day8/main.js";
import * as day9 from "./day9/main.js";
import * as day10 from "./day10/main.js";
import * as day11 from "./day11/main.js";
import * as day12 from "./day12/main.js";
import * as day13 from "./day13/main.js";
import * as day14 from "./day14/main.js";

day1.partOne();
day1.partTwo();
day2.partOne();
day2.partTwo();
day3.partOne();
day3.partTwo();
day4.partOne();
day4.partTwo();
day5.partOne();
console.log({ day: 5, part: 2, value: "Manual Run required" });
// day5.partTwo(); // This takes ages so will comment out
day6.partOne();
day6.partTwo();
day7.partOne();
day7.partTwo();
day8.partOne();
day8.partTwo();
day9.partOne();
day9.partTwo();
day10.partOne();
day10.partTwo();
day11.partOne();
day11.partTwo();
day12.partOne();
day12.partTwo();
day13.partOne();
day13.partTwo();
day14.partOne();
day14.partTwo();
