import * as dayOne from "./day1/main.js";
import * as dayTwo from "./day2/main.js";
import * as dayThree from "./day3/main.js";
import * as dayFour from "./day4/main.js";
import * as dayFive from "./day5/main.js";
import * as daySix from "./day6/main.js";
import * as daySeven from "./day7/main.js";
import * as dayEight from "./day8/main.js";
import * as dayNine from "./day9/main.js";
import * as dayTen from "./day10/main.js";
import * as dayEleven from "./day11/main.js";
import * as dayTwelve from "./day12/main.js";

dayOne.partOne();
dayOne.partTwo();
dayTwo.partOne();
dayTwo.partTwo();
dayThree.partOne();
dayThree.partTwo();
dayFour.partOne();
dayFour.partTwo();
dayFive.partOne();
console.log({ day: 5, part: 2, value: "Manual Run required" });
// dayFive.partTwo(); // This takes ages so wil comment out
daySix.partOne();
daySix.partTwo();
daySeven.partOne();
daySeven.partTwo();
dayEight.partOne();
dayEight.partTwo();
dayNine.partOne();
dayNine.partTwo();
dayTen.partOne();
dayTen.partTwo();
dayEleven.partOne();
dayEleven.partTwo();
dayTwelve.partOne();
dayTwelve.partTwo("input");
