import * as day01 from "./day01/main.js";
import * as day02 from "./day02/main.js";
import * as day03 from "./day03/main.js";
import * as day04 from "./day04/main.js";
import * as day05 from "./day05/main.js";
import * as day06 from "./day06/main.js";
import * as day07 from "./day07/main.js";
import * as day08 from "./day08/main.js";
import * as day09 from "./day09/main.js";
import * as day10 from "./day10/main.js";
import * as day11 from "./day11/main.js";
import * as day12 from "./day12/main.js";
import * as day13 from "./day13/main.js";
import * as day14 from "./day14/main.js";
import * as day15 from "./day15/main.js";
import * as day16 from "./day16/main.js";
import * as day17 from "./day17/main.js";
import * as day18 from "./day18/main.js";
import * as day19 from "./day19/main.js";
import * as day20 from "./day20/main.js";
import * as day21 from "./day21/main.js";
import * as day22 from "./day22/main.js";
import * as day23 from "./day23/main.js";
import * as day24 from "./day24/main.js";
import * as day25 from "./day25/main.js";

day01.partOne();
day01.partTwo();
day02.partOne();
day02.partTwo();
day03.partOne();
day03.partTwo();
day04.partOne();
day04.partTwo();
day05.partOne();
console.log({ day: 5, part: 2, value: "Manual Run required" });
// day05.partTwo(); // This takes ages so will comment out
day06.partOne();
day06.partTwo();
day07.partOne();
day07.partTwo();
day08.partOne();
day08.partTwo();
day09.partOne();
day09.partTwo();
day10.partOne();
day10.partTwo();
day11.partOne();
day11.partTwo();
day12.partOne();
day12.partTwo();
day13.partOne();
day13.partTwo();
day14.partOne();
day14.partTwo();
day15.partOne();
day15.partTwo();
day16.partOne();
day16.partTwo();
day17.partOne();
day17.partTwo();
day18.partOne();
day18.partTwo();
day19.partOne();
day19.partTwo();
day20.partOne();
// day20.partTwo("input");
console.log({ day: 20, part: 2, value: "Input and Manual Run Required" }); // Input must be day 20's for this to work
day21.partOne();
// day21.partTwo("input");
console.log({ day: 21, part: 2, value: "Input and Manual Run Required" }); // Input must be day 21's for this to work
day22.partOne();
day22.partTwo();
day23.partOne();
day23.partTwo();
day24.partOne();
// await day24.partTwo();
console.log({ day: 24, part: 2, value: "Manual Run Required" }); // Is a bit slow so will comment out
day25.partOne();
day25.partTwo();